config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  root 'pins#index'
  get '/main' => 'pins#index'
  get 'pins/quiz'
  post 'pins' => 'pins#create'
  get 'pins/new' => 'pins#new', as: 'new_pin'

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def index
    @characters = ['cinderella','snowwhite','belle']
  end

  def new
    @pin = Pin.new
  end

  def create
    pin = Pin.new(pin_params)
    if pin.save
      redirect_to :users_index
    else
      redirect_to :back
    end
  end


  def pin_params
    params.require(:pin).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @pins = Pin.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to image_tag('logo.png'), main_path, class: 'icon' %>
    <%= link_to image_tag('mypage.png'), users_index_path, class: 'icon' %>
    <%= link_to 'new', new_pin_path %>
    <%= link_to 'Facebook', "https://www.facebook.com/games/pinterestapp", target: '_blank' %>
    <%= yield %>
  </body>
</html>

app/views/pins/index.html.erb
<div id="columns">
  <figure>
    <%= image_tag 'disney/cinderella.jpg' %>
    <figcaption><%= @characters[0].capitalize %> wearing European fashion of the mid-1860’s</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/rapunzel.jpg' %>
    <figcaption>Rapunzel, clothed in 1820’s period fashion</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/belle.jpg' %>
    <figcaption>Belle, based on 1770’s French court fashion</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/mulan_2.jpg' %>
    <figcaption>Mulan, based on the Ming Dynasty period</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/sleeping-beauty.jpg' %>
    <figcaption>Sleeping Beauty, based on European fashions in 1485</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/pocahontas_2.jpg' %>
    <figcaption>Pocahontas based on 17th century Powhatan costume</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/snow-white.jpg' %>
    <figcaption>Snow White, based on 16th century German fashion</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/ariel.jpg' %>
    <figcaption>Ariel wearing an evening gown of the 1890’s</figcaption>
  </figure>

  <figure>
    <%= image_tag 'disney/tiana.jpg' %>
    <!--<img src="//s3-us-west-2.amazonaws.com/s.cdpn.io/4273/tiana.jpg">-->
    <figcaption>Tiana wearing the <i>robe de style</i> of the 1920’s</figcaption>
  </figure>
</div>

app/views/pins/new.html.erb
<%= form_for @pin do |f| %>

  <%= f.text_field :body %> <br>

  <%= f.submit 'submit' %>

<% end %>

app/views/pins/quiz.html.erb
<style>
  #outer {
    width: 300px;
    margin: 0px auto;
  }
  #pins {
    border:1px solid rgba(0,0,0,0.2);
    padding:10px;
  }
  #pins #desc {
    text-align: center;
    color: #EC9800;
  }
  #pins img {
    width: 100%;
  }
</style>

<div id="outer">
  <div id="pins">
    <img src="//s3-us-west-2.amazonaws.com/s.cdpn.io/4273/belle.jpg">
    <div id="desc">belle</div>
  </div>
</div>

app/views/users/index.html.erb
<% @pins.each do |p| %>
  <%= p.body %> <br>
<% end %>